In [1]:
import pandas as pd
from sqlalchemy import create_engine
import json
from pymongo import MongoClient

In [2]:
client = MongoClient('localhost', 27017)
db = client['SF_Restaurant_db']

In [3]:
csv_file = "Resources/FAO.csv"
Raw_Master_df = pd.read_csv(csv_file , encoding='latin-1')
Raw_Master_df.head(5)

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,...,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,...,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,...,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422
2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,...,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360
3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,...,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89
4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,...,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200

In [4]:
wine_df = Raw_Master_df[Raw_Master_df["Item"].str.match("Wine")]
wine_df.fillna(0)
Clean_wine_df = wine_df.fillna(0)
Clean_wine_df.to_csv("Clean_wine_df.csv")

In [5]:
Alcoholic_Beverages_df = Raw_Master_df[Raw_Master_df["Item"].str.match("Alcoholic Beverages")]
Alcoholic_Beverages_df
Alcoholic_Beverages_df.fillna(0)
Clean_Alcoholic_Beverages_df = Alcoholic_Beverages_df.fillna(0)
Clean_Alcoholic_Beverages_df.to_csv("Clean_Alcoholic_Beverages_df.csv")

In [6]:
Alcoholic_Beverages_df.head()

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,...,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
74,AFG,2,Afghanistan,2924,Alcoholic Beverages,5142,Food,1000 tonnes,33.94,67.71,...,5.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3,3
195,ALB,3,Albania,2924,Alcoholic Beverages,5142,Food,1000 tonnes,41.15,20.17,...,70.0,71.0,80.0,90.0,89.0,85.0,108.0,121.0,116,119
320,DZA,4,Algeria,2924,Alcoholic Beverages,5142,Food,1000 tonnes,28.03,1.66,...,115.0,130.0,137.0,145.0,158.0,147.0,149.0,157.0,166,196
427,AGO,7,Angola,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-11.20,17.87,...,506.0,571.0,746.0,772.0,1019.0,1149.0,1342.0,1482.0,1760,1761
545,ATG,8,Antigua and Barbuda,2924,Alcoholic Beverages,5142,Food,1000 tonnes,17.06,-61.80,...,2.0,2.0,3.0,3.0,3.0,2.0,2.0,3.0,2,3

In [7]:
Booze_df = pd.concat([Alcoholic_Beverages_df , wine_df], ignore_index = True)

In [8]:
Master_Booze_df = Booze_df.sort_values('Area')

In [9]:
Master_Booze_df

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,...,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,AFG,2,Afghanistan,2924,Alcoholic Beverages,5142,Food,1000 tonnes,33.94,67.71,...,5.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3,3
173,AFG,2,Afghanistan,2655,Wine,5142,Food,1000 tonnes,33.94,67.71,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0,0
174,ALB,3,Albania,2655,Wine,5142,Food,1000 tonnes,41.15,20.17,...,15.0,19.0,19.0,20.0,19.0,20.0,23.0,24.0,24,25
1,ALB,3,Albania,2924,Alcoholic Beverages,5142,Food,1000 tonnes,41.15,20.17,...,70.0,71.0,80.0,90.0,89.0,85.0,108.0,121.0,116,119
2,DZA,4,Algeria,2924,Alcoholic Beverages,5142,Food,1000 tonnes,28.03,1.66,...,115.0,130.0,137.0,145.0,158.0,147.0,149.0,157.0,166,196
175,DZA,4,Algeria,2655,Wine,5142,Food,1000 tonnes,28.03,1.66,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
176,AGO,7,Angola,2655,Wine,5142,Food,1000 tonnes,-11.20,17.87,...,58.0,75.0,86.0,88.0,116.0,80.0,91.0,95.0,103,100
3,AGO,7,Angola,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-11.20,17.87,...,506.0,571.0,746.0,772.0,1019.0,1149.0,1342.0,1482.0,1760,1761
177,ATG,8,Antigua and Barbuda,2655,Wine,5142,Food,1000 tonnes,17.06,-61.80,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0,1
4,ATG,8,Antigua and Barbuda,2924,Alcoholic Beverages,5142,Food,1000 tonnes,17.06,-61.80,...,2.0,2.0,3.0,3.0,3.0,2.0,2.0,3.0,2,3
5,ARG,9,Argentina,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-38.42,-63.62,...,2436.0,2502.0,2553.0,2620.0,2838.0,2818.0,2760.0,2726.0,2730,2950
178,ARG,9,Argentina,2655,Wine,5142,Food,1000 tonnes,-38.42,-63.62,...,1113.0,1099.0,1112.0,1117.0,1068.0,1035.0,976.0,982.0,1008,1038
179,ARM,1,Armenia,2655,Wine,5142,Food,1000 tonnes,40.07,45.04,...,7.0,7.0,4.0,3.0,3.0,4.0,5.0,6.0,4,4
6,ARM,1,Armenia,2924,Alcoholic Beverages,5142,Food,1000 tonnes,40.07,45.04,...,24.0,25.0,27.0,27.0,27.0,31.0,33.0,23.0,17,24
7,AUS,10,Australia,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-25.27,133.78,...,2236.0,2311.0,2297.0,2316.0,2250.0,2418.0,2298.0,2416.0,2488,2610
180,AUS,10,Australia,2655,Wine,5142,Food,1000 tonnes,-25.27,133.78,...,437.0,457.0,464.0,487.0,485.0,513.0,536.0,456.0,458,455
8,AUT,11,Austria,2924,Alcoholic Beverages,5142,Food,1000 tonnes,47.52,14.55,...,1182.0,1205.0,1211.0,1191.0,1151.0,1193.0,1174.0,1202.0,1172,1222
181,AUT,11,Austria,2655,Wine,5142,Food,1000 tonnes,47.52,14.55,...,246.0,266.0,270.0,244.0,246.0,269.0,257.0,260.0,250,269
182,AZE,52,Azerbaijan,2655,Wine,5142,Food,1000 tonnes,40.14,47.58,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2,2
9,AZE,52,Azerbaijan,2924,Alcoholic Beverages,5142,Food,1000 tonnes,40.14,47.58,...,228.0,297.0,374.0,458.0,406.0,449.0,475.0,488.0,555,616
183,AZE,12,Bahamas,2655,Wine,5142,Food,1000 tonnes,25.03,-77.40,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2,2
10,AZE,12,Bahamas,2924,Alcoholic Beverages,5142,Food,1000 tonnes,25.03,-77.40,...,10.0,9.0,9.0,9.0,9.0,10.0,9.0,10.0,9,8
184,BGD,16,Bangladesh,2655,Wine,5142,Food,1000 tonnes,23.68,90.36,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
11,BGD,16,Bangladesh,2924,Alcoholic Beverages,5142,Food,1000 tonnes,23.68,90.36,...,2.0,0.0,3.0,3.0,3.0,4.0,5.0,4.0,3,3
185,BRB,14,Barbados,2655,Wine,5142,Food,1000 tonnes,13.19,-59.54,...,1.0,2.0,2.0,2.0,3.0,3.0,2.0,2.0,2,2
12,BRB,14,Barbados,2924,Alcoholic Beverages,5142,Food,1000 tonnes,13.19,-59.54,...,9.0,14.0,14.0,15.0,15.0,15.0,16.0,15.0,18,18
186,BLR,57,Belarus,2655,Wine,5142,Food,1000 tonnes,53.71,27.95,...,58.0,63.0,64.0,68.0,72.0,64.0,74.0,74.0,79,82
13,BLR,57,Belarus,2924,Alcoholic Beverages,5142,Food,1000 tonnes,53.71,27.95,...,382.0,505.0,599.0,694.0,730.0,684.0,735.0,753.0,755,739
14,BEL,255,Belgium,2924,Alcoholic Beverages,5142,Food,1000 tonnes,50.50,4.47,...,1260.0,1361.0,1302.0,1239.0,1208.0,1227.0,1224.0,1307.0,1180,1177
187,BEL,255,Belgium,2655,Wine,5142,Food,1000 tonnes,50.50,4.47,...,284.0,286.0,299.0,297.0,291.0,303.0,285.0,313.0,307,305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,TUR,223,Turkey,2655,Wine,5142,Food,1000 tonnes,38.96,35.24,...,23.0,23.0,21.0,17.0,23.0,21.0,26.0,27.0,30,29
158,TUR,223,Turkey,2924,Alcoholic Beverages,5142,Food,1000 tonnes,38.96,35.24,...,837.0,899.0,916.0,920.0,1026.0,1007.0,1040.0,1069.0,1057,1038
328,TKM,213,Turkmenistan,2655,Wine,5142,Food,1000 tonnes,38.97,59.56,...,43.0,44.0,44.0,45.0,39.0,40.0,39.0,39.0,39,39
159,TKM,213,Turkmenistan,2924,Alcoholic Beverages,5142,Food,1000 tonnes,38.97,59.56,...,56.0,59.0,57.0,51.0,45.0,43.0,44.0,43.0,42,43
329,UGA,226,Uganda,2655,Wine,5142,Food,1000 tonnes,1.37,32.29,...,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,2,2
160,UGA,226,Uganda,2924,Alcoholic Beverages,5142,Food,1000 tonnes,1.37,32.29,...,3464.0,3582.0,3616.0,3600.0,2550.0,2504.0,2719.0,2943.0,2943,2763
161,UKR,230,Ukraine,2924,Alcoholic Beverages,5142,Food,1000 tonnes,48.38,31.17,...,2549.0,2826.0,3146.0,3661.0,3654.0,3366.0,3617.0,3508.0,3365,3160
330,UKR,230,Ukraine,2655,Wine,5142,Food,1000 tonnes,48.38,31.17,...,189.0,202.0,237.0,273.0,272.0,226.0,267.0,240.0,182,178
331,GBR,229,United Kingdom,2655,Wine,5142,Food,1000 tonnes,55.38,-3.44,...,1090.0,1295.0,1158.0,1150.0,1058.0,1072.0,1192.0,1268.0,1241,1185
162,GBR,229,United Kingdom,2924,Alcoholic Beverages,5142,Food,1000 tonnes,55.38,-3.44,...,7337.0,7503.0,7069.0,6894.0,6639.0,6090.0,6248.0,6447.0,6089,5904
332,TZA,215,United Republic of Tanzania,2655,Wine,5142,Food,1000 tonnes,-6.37,34.89,...,1.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,6,6
163,TZA,215,United Republic of Tanzania,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-6.37,34.89,...,2301.0,2369.0,2596.0,3027.0,2277.0,2946.0,3202.0,3344.0,2945,3280
333,USA,231,United States of America,2655,Wine,5142,Food,1000 tonnes,37.09,-95.71,...,2152.0,2177.0,2128.0,2126.0,2130.0,2208.0,2206.0,2305.0,2607,2710
164,USA,231,United States of America,2924,Alcoholic Beverages,5142,Food,1000 tonnes,37.09,-95.71,...,29971.0,30296.0,30543.0,30618.0,30397.0,30026.0,30147.0,29713.0,30494,30053
334,URY,234,Uruguay,2655,Wine,5142,Food,1000 tonnes,-32.52,-55.77,...,104.0,100.0,93.0,87.0,69.0,64.0,71.0,80.0,78,66
165,URY,234,Uruguay,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-32.52,-55.77,...,191.0,188.0,185.0,181.0,160.0,157.0,165.0,181.0,185,175
335,UZB,235,Uzbekistan,2655,Wine,5142,Food,1000 tonnes,41.38,64.59,...,35.0,23.0,22.0,24.0,24.0,12.0,13.0,31.0,29,29
166,UZB,235,Uzbekistan,2924,Alcoholic Beverages,5142,Food,1000 tonnes,41.38,64.59,...,172.0,179.0,204.0,206.0,232.0,289.0,362.0,367.0,335,331
336,VUT,155,Vanuatu,2655,Wine,5142,Food,1000 tonnes,-15.38,166.96,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
167,VUT,155,Vanuatu,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-15.38,166.96,...,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1,1
337,VEN,236,Venezuela (Bolivarian Republic of),2655,Wine,5142,Food,1000 tonnes,6.42,-66.59,...,12.0,16.0,24.0,28.0,26.0,20.0,12.0,19.0,22,11
168,VEN,236,Venezuela (Bolivarian Republic of),2924,Alcoholic Beverages,5142,Food,1000 tonnes,6.42,-66.59,...,2139.0,2334.0,2538.0,2679.0,2584.0,2445.0,2298.0,2122.0,2221,2090
338,VNM,237,Viet Nam,2655,Wine,5142,Food,1000 tonnes,14.06,108.28,...,5.0,5.0,6.0,8.0,7.0,9.0,10.0,13.0,12,12
169,VNM,237,Viet Nam,2924,Alcoholic Beverages,5142,Food,1000 tonnes,14.06,108.28,...,1043.0,1149.0,1039.0,1192.0,1196.0,1302.0,1357.0,1419.0,1466,1520
339,YEM,249,Yemen,2655,Wine,5142,Food,1000 tonnes,15.55,48.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
170,YEM,249,Yemen,2924,Alcoholic Beverages,5142,Food,1000 tonnes,15.55,48.52,...,11.0,8.0,9.0,11.0,9.0,7.0,15.0,9.0,11,11
171,ZMB,251,Zambia,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-13.13,27.85,...,313.0,292.0,339.0,293.0,315.0,359.0,383.0,405.0,418,449
340,ZMB,251,Zambia,2655,Wine,5142,Food,1000 tonnes,-13.13,27.85,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
172,ZWE,181,Zimbabwe,2924,Alcoholic Beverages,5142,Food,1000 tonnes,-19.02,29.15,...,294.0,290.0,316.0,355.0,398.0,437.0,448.0,476.0,525,516
341,ZWE,181,Zimbabwe,2655,Wine,5142,Food,1000 tonnes,-19.02,29.15,...,2.0,2.0,2.0,2.0,3.0,3.0,4.0,3.0,4,4

In [10]:
Master_Booze_df.to_csv("Master_Booze_df.csv")

In [11]:
for col in Clean_Alcoholic_Beverages_df: 
    print(col)

Area Abbreviation
Area Code
Area
Item Code
Item
Element Code
Element
Unit
latitude
longitude
Y1961
Y1962
Y1963
Y1964
Y1965
Y1966
Y1967
Y1968
Y1969
Y1970
Y1971
Y1972
Y1973
Y1974
Y1975
Y1976
Y1977
Y1978
Y1979
Y1980
Y1981
Y1982
Y1983
Y1984
Y1985
Y1986
Y1987
Y1988
Y1989
Y1990
Y1991
Y1992
Y1993
Y1994
Y1995
Y1996
Y1997
Y1998
Y1999
Y2000
Y2001
Y2002
Y2003
Y2004
Y2005
Y2006
Y2007
Y2008
Y2009
Y2010
Y2011
Y2012
Y2013

In [16]:
rds_connection_string =rds_connection_string = "postgres:Estarrol88@localhost:5432/Worldproduction_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [17]:
engine.table_names()

['Alcoholic_Beverages']

In [19]:
Clean_Alcoholic_Beverages_df.to_sql(name='Alcoholic_Beverages', con=engine, if_exists='append', index=False)